# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-10 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_auto_20160707_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='id',
        ),
        migrations.AlterField(
            model_name='sale',
            name='n_sale',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
