# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20160709_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'permissions': (('to_access_sale', 'Puede acceder a ventas'),)},
        ),
    ]
