# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-11 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20160711_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_sale',
            field=models.DateField(blank=True, null=True),
        ),
    ]
